#!/usr/bin/env bash
#
# A wizard walks a human through a manual procedure, step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library: delightful, consistent UX, identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear wipes the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" shows the opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later, since it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" clears the screen, then announces a stage and shows progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." prints a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." is a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL opens it in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser; visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser, so visit it manually: $url"
}

# pause "msg" waits for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" is a y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY: current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" reads a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" is like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE upserts KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE sets a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name: gh not ready; set it later"
}

# set_var NAME VALUE sets a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name, gh not ready; set it later"
}

# finish clears, then shows a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES: deploy agent "researcher" (gpt-researcher lokal)
# Dibuat DevOps. Menjalankan langkah manual yang hanya bisa dilakukan CEO:
# memilih search provider, menyimpan env, dan menyetujui deploy.
# Jalankan dari root INSTALASI BABD, bukan dari worktree.
# ──────────────────────────────────────────────────────────────────────────

INSTALL_ROOT="${BABD_INSTALL_ROOT:-$(pwd)}"
ENV_FILE="${ENV_FILE:-${INSTALL_ROOT}/.env}"
DASHBOARD="${BABD_DASHBOARD_URL:-http://127.0.0.1:8800}"
VENV_PY="${INSTALL_ROOT}/.venv/bin/python"

TOTAL_STAGES=4

banner "Deploy agent researcher"

# ── Stage 1: pilih search provider ────────────────────────────────────────
stage "Pilih search provider"
say "researcher butuh sumber pencarian internet. Tanpa provider, adapter berhenti"
say "dengan exit 2 secara jujur (tidak mengarang sumber) — agent ada tapi belum operasional."
say ""
note "searxng-lokal : SearXNG di mesin ini (URL mis. http://127.0.0.1:8888)"
note "duckduckgo    : fallback tanpa API key (ketik 1 untuk mengizinkan)"
note "tavily        : butuh API key (rahasia), hanya bila CEO menyediakannya"
say ""
ask RESEARCHER_PROVIDER "Provider [searxng-lokal/duckduckgo/tavily]: "

case "$RESEARCHER_PROVIDER" in
  searxng-lokal)
    step "Masukkan URL SearXNG lokal Anda (contoh: http://127.0.0.1:8888)."
    ask RESEARCHER_SEARXNG_URL "URL SearXNG:"
    write_env RESEARCHER_SEARXNG_URL "$RESEARCHER_SEARXNG_URL"
    ;;
  duckduckgo)
    warn "DuckDuckGo adalah fallback tanpa jaminan; kualitas & rate-limit bervariasi."
    if confirm "Izinkan fallback DuckDuckGo untuk researcher?"; then
      write_env RESEARCHER_ALLOW_DUCKDUCKGO "1"
    else
      note "Tidak diizinkan: researcher akan exit 2 sampai provider lain diset."
    fi
    ;;
  tavily)
    step "Buka dashboard Tavily, tab API Keys, lalu copy key-nya."
    open_url "https://app.tavily.com/home"
    ask_secret TAVILY_API_KEY "Paste API key Tavily:"
    write_env TAVILY_API_KEY "$TAVILY_API_KEY"
    warn "Pastikan adapter memang membaca TAVILY_API_KEY; wizard hanya menyimpan rahasianya."
    if confirm "Set TAVILY_API_KEY juga sebagai GitHub secret untuk CI?"; then
      set_secret TAVILY_API_KEY "$TAVILY_API_KEY"
    fi
    ;;
  *)
    warn "'${RESEARCHER_PROVIDER:-<kosong>}' tidak dikenal — tidak ada provider yang diset."
    note "researcher akan berhenti dengan exit 2 sampai wizard dijalankan ulang."
    SKIPPED+=("set search provider untuk researcher")
    ;;
esac

pause "Pencatatan provider selesai. Lanjut?"

# ── Stage 2: pastikan runtime lokal terpasang ─────────────────────────────
stage "Runtime lokal (vendor + venv)"
say "researcher memakai gpt-researcher yang di-vendor di .babd/researcher/."
say "Setup ini idempoten dan aman diulang."
SETUP_BIN="${INSTALL_ROOT}/.babd/researcher/bin/setup"
if [[ -x "$SETUP_BIN" ]]; then
  if confirm "Jalankan .babd/researcher/bin/setup sekarang (butuh jaringan keluar sekali)?"; then
    if bash "$SETUP_BIN"; then
      note "Setup selesai."
    else
      warn "Setup GAGAL. Bila karena jaringan, researcher belum operasional (mode jujur exit 2)."
      SKIPPED+=("setup runtime researcher (.babd/researcher/bin/setup) saat jaringan tersedia")
    fi
  fi
else
  warn ".babd/researcher/bin/setup belum ada."
  note "Minta Developer menyiapkan scripts/researcher_setup.sh lebih dulu, lalu ulangi wizard."
  SKIPPED+=("runtime lokal researcher belum dipasang")
fi

# ── Stage 3: cek sehat sebelum menyetujui ─────────────────────────────────
stage "Cek sehat"
say "Sebelum menyetujui deploy, pastikan perintah harness ditemukan (path absolut)."
CHECK="${INSTALL_ROOT}/scripts/researcher_deploy_check.sh"
if [[ -x "$CHECK" ]]; then
  if confirm "Jalankan scripts/researcher_deploy_check.sh sekarang?"; then
    bash "$CHECK" || warn "Satu atau lebih check GAGAL — jangan deploy dulu."
  fi
else
  note "Script check belum ada; jalankan perintah manual di RUNBOOK bagian Health check."
fi
say ""
step "Bila ada check yang GAGAL, STOP. Laporkan ke Team Lead; jangan setujui deploy."

pause "Lanjut ke persetujuan?"

# ── Stage 4: setujui deploy di dashboard ──────────────────────────────────
stage "Persetujuan deploy (CEO)"
say "Deploy dijalankan flow BABD hanya setelah QA PASS dan persetujuan Anda."
say "Buka dashboard, lihat panel persetujuan, lalu Approve atau Reject."
open_url "$DASHBOARD"
step "Lihat kartu task researcher / panel 'waiting_ceo'."
step "Klik Approve untuk mengizinkan langkah deploy, atau Reject untuk menahan."
say ""
if confirm "Sudah Anda putuskan di dashboard (Approve/Reject)?"; then
  note "Bagus. Restart service dilakukan manual oleh DevOps/root:"
  note "  systemctl restart babd-dashboard.service && systemctl is-active babd-dashboard.service"
else
  SKIPPED+=("keputusan deploy di dashboard (Approve/Reject)")
fi

finish
